typography_spectrum: 0.614570849807933
color:
  brandStrength: 0.6098207761533558
  lightness: 0.17869455204345286
  saturation: 0.7757481462322176
  rhythmicContrast: 0.6697860893327743
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.14229644532315433
name: raffmix.com
description: technology is just a to to express creativity
